---
#-------------------------------
# Site Settings
title: HyperEcho
description: Homebase for cloud solution projects and innovative technology blogs!
logo: "/images/logo2.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo2-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Blog"
      url: "/posts/"
    # - title: "Resources"
    #   submenu:
    #     - url: "/posts/the-psychology-of-mobile-app-colors-influencing-user-perception"
    #       title: "News"
    #     - url: "/posts/gamifying-the-user-experience-strategies-beyond-mobile-games"
    #       title: "Games"
    #     - url: "/posts/harmonizing-aesthetics-and-functionality-in-ux-ui-mobile-design"
    #       title: "Mobile"
    #     - url: "/elements/"
    #       title: "Elements"
    - title: "About Me"
      url: "/about/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: "/contact/"
  cta_button_text: Get in touch

#-------------------------------
# Author Settings
author:
  author_name: "Dylan Hover"
  author_avatar: "/images/Profile PicNew2.svg"

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Experienced Systems Administrator specializing in deploying solutions for hybrid environments.
  hero_description: As an enterprise-level Systems Administrator for on-premises and cloud environments I can assist with designing robust, scalable architectures that align with business goals. I have collaborated seamlessly across teams, leveraging innovative technologies to deliver secure, efficient, and future-ready solutions. Icons by <a target="_blank" href="https://icons8.com">Icons8</a>

# Hero Logos
hero_logos:
  enable: true

hero_logo_image:
  - alt: "Azure Logo"
    image: "/images/azure.svg"

  - alt: "Docker Logo"
    image: "/images/docker.svg"

  - alt: "Kubernetes Logo"
    image: "/images/kubernetes.svg"

  - alt: "Terraform Logo"
    image: "/images/terraform.svg"

  - alt: "AWS Logo"
    image: "/images/aws.svg"

  - alt: "Dropbox Logo"
    image: "/images/dropbox.svg"

  - alt: "VMWare Logo"
    image: "/images/vmware.svg"

  - alt: "Google Cloud Logo"
    image: "/images/google-cloud.svg"

#-------------------------------
# Slider Featured Settings
featured:
  enable: true
  featured_title: Projects

#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: Recent Work
  projects_description:

#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: false
  testimonials_intro: Don't take my word for it
  testimonials_title: See what our happy clients say...
  testimonials_info: Join over <b>10K+</b> Prefessionals

testimonial_items:
  - name: "Martin Vetrovs"
    image: "/images/client-1.jpg"
    designation: "Data Scientist"
    title: "Incredible attention to detail"
    content: "The incredible attention to detail displayed by this team is commendable. Every aspect of our project, no matter how small, was handled with precision and care. The result is a product that reflects their commitment to excellence."

  - name: "Hanna Herwitz"
    image: "/images/client-2.jpg"
    designation: "Designer"
    title: "Collaborative partnership"
    content: "Our partnership with this team was characterized by open communication and collaborative efforts. They took the time to understand our goals and delivered a solution that perfectly aligns with our business objectives. Looking forward to future collaborations."

  - name: "Carter Curtis"
    image: "/images/client-3.jpg"
    designation: "DevOps Engineer"
    title: "Creative brilliance unleashed"
    content: "Working with this creative powerhouse was an enlightening experience. Their brilliance in design thinking and creative solutions brought our project to life in ways we hadn't imagined. The team's passion for innovation is truly infectious."

  - name: "Marcus Vaccaro"
    image: "/images/client-4.jpg"
    designation: "Systems Analyst"
    title: "Efficient problem solvers"
    content: "This team proved to be efficient problem solvers throughout our project. When faced with challenges, they tackled them with creativity and resourcefulness. Their ability to overcome obstacles ensured a smooth and successful project delivery."

#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: true
  faq_title: Frequently asked questions
  faq_intro: Need some answers?
  faq_items:
    - title: What distinguishes you as a cloud solutions architect?
      description: My ability to seamlessly bridge on-premises and cloud environments with a focus on aligning technical solutions with business objectives sets me apart. I leverage innovative technologies to design architectures that are secure, scalable, and future-ready.
    - title: How do you approach designing cost effective solutions to businesses?
      description: I prioritize understanding the unique needs and budget constraints of the business, then design solutions that maximize resource efficiency. I leverage cloud-native services, right-sizing, and automation to optimize costs without sacrificing performance.
    - title: How can you help our business to develop resilient, and scalable technology solutions?
      description: I design architectures with built-in redundancy, automated failover, and scalability to ensure high availability and resilience. By adopting a modular approach, I enable easy scaling and adaptability as the business grows and evolves.
    - title: How do you stay updated on the latest trends in the technology industry?
      description: Continuous learning is key. I regularly engage with industry publications, attend webinars and conferences, and participate in professional communities. Continuous learning and hands-on experimentation with new technologies ensure I remain at the forefront of industry developments.
    - title: How do you implement security best practices in your cloud architecture solutions?
      description: I incorporate security from the outset by following the principle of least privilege, encrypting data in transit and at rest, and implementing robust identity and access management controls. Regular audits and updates to security policies ensure ongoing protection against emerging threats.

#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_intro: What‚Äôs new?
  blog_title: Latest from blog

#-------------------------------
# Author Section Settings
author_section:
  enable: true
  author_section_title: "Welcome to my journey into the cloud. My name is Dylan. I am a cloud enthusiast, fly-fisherman, husband to my lovely wife and father to three beautiful kids."
  author_section_description: When I'm not designing cloud architecture solutions, you'll find me enjoying a hot cup of coffee, camping with my family, fly fishing in the rivers of the Northwest, or planning our next adventure. Let's collaborate together, and build the applications of the future. Cheers to good vibes and creative adventures!
  author_section_image: "/images/Profile-Pic3.jpg"
  author_section_image_alt: Dylan Hover
  author_section_button_text: Let's —Åonnect!
  author_section_button_link: "/contact/"

#-------------------------------
# Footer Settings

# Footer Navigation
footer_menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Posts"
      url: "/posts/"
    - url: "/about/"
      title: "About Me"

# Social Links
social:
  - {
      icon: "fa-brands fa-facebook-f",
      name: "Facebook",
      link: "https://facebook.com",
    }
  - {
      icon: "fa-brands fa-x-twitter",
      name: "Twitter",
      link: "https://twitter.com",
    }
  - {
      icon: "fa-brands fa-tiktok",
      name: "Tiktok",
      link: "https://www.tiktok.com",
    }
  - {
      icon: "fa-brands fa-instagram",
      name: "Instagram",
      link: "https://instagram.com",
    }

# Example of adding a new link to the footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Stay inspired weekly üì¨ Your friendly dose of tips & insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address

#-------------------------------
# Contact Settings
contact:
  email: dylan.m.hover@gmail.com # Add your form_id
  description: Have a question or interested in collaborating? Feel free to reach out! Use the form below to send me a message, and I'll get back to you as soon as possible. Whether it's about cloud solutions, hybrid infrastructure, or a new project idea, I'm happy to connect! # Add a description of your form

# NOTE
# Gerous theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test

#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
